### PR TITLE
cmd/gocharm: set charm name

### PR DESCRIPTION
**Pull request by martijn4evers**
Hi,

I am using your project to build a charm. I needed the 'name' flag and saw it wasn't implemented yet. So I've added it.

Kind Regards,
Martijn Evers

### CODE REVIEW

**Comment by rogpeppe** [comment]
Thanks very much for the pull request! Before committing this change,
I'd like to understand a little more about your use case. In particular, why is it
not reasonable for you to name the Go package after the destination charm name?

The main reason I'm asking is it has vaguely been on my mental roadmap
that gocharm could take a list of packages as arguments, and in that context,
a flag that applies to a single charm only doesn't fit very well.

Thanks again for your contribution.

**Comment by martijn4evers** [comment]
I already got an daemon written in Go that was supposed to run in the unit to perform support tasks (keep 3rd-party software up-to-date and stuff). In a separate project I developed a charm to deploy this daemon, but when I came across your project I decided to make a 'charm' package in the daemon project. To sum up:

```bash
/projects/
    /3rd-party-software
    /daemon # maintains 3rd-party software
        /charm # charm package replaces /projects/charm
    /charm # is going to be replaced, has a pleasant charm name ;)
```
I need the name flag to build a charm with this command:
```bash
cd /projects/daemon/charm
gocharm -name=daemon
```
Without it the charm name would be 'charm'.

Now I'm thinking to change the daemon into a charm. It seems logical. The only piece I was missing was 'charmbits/service', which I think is brilliant. If the daemon becomes a charm I can launch it as a service.

I let you know if that works for me.

**Comment by rogpeppe** [comment]
Would it be a significant problem to name your charm package
"daemon/charms/daemon" or "charms/daemon" or even "daemon/daemon"?

I'm glad you like charmbits/service, but I know there are some things that
need some work! Please raise issues for any roadblocks or annoyances that
you find.  That will help me prioritise work done in any time I find to
work on gocharm.

**Comment by martijn4evers** [comment]
The daemon *is* a charm now. I did some refactoring and this looks like a better solution. Even code calling into the service using RPC works good. Less code and it works like a charm, pun intended ;)

Anyhow I think none of your proposed package organizations would impose significant problems. I do not think you should limit gocharm to process multiple packages, my use-case isn't that significant. Seeing https://github.com/juju/gocharm/blob/ee7a68ecffe8444456e86ed1b48a8c8942ed3c89/cmd/gocharm/main.go#L30 caused me to think this feature was already on the roadmap. So I tried to do you a favor and implement it :) I am glad to leave this PR if it is not a direction you want to take.

But if a need arises for naming packages. Maybe an other solution is to take the name of the charm from the metadata.yaml file. I noticed that the summary, description and tags where already taken from that file.

**Comment by rogpeppe** [comment]
Seems like you managed to do without this, so closing this pending a more pressing use case. Thanks anyway!

**Pull request closed without merging**
